### ISSUE TITLE
Xbox 1.4

### ISSUE THREAD

**Issue by danko79** [Electrical5/ModXo-RP2040-Zero#1]
Hi, i have a problem with this RP2040 adapter on my Xbox 1.4 soldered only pin header in according on this schematic https://raw.githubusercontent.com/Team-Resurgent/Modxo/refs/heads/main/images/lpc_header_wiring.png

The RP2040 Zero Tiny buy on aliexpress clone boards that are not compatible? several times test when power on the console not boot no video.

For install .uf2 this tutorial for flash 3 file https://www.youtube.com/watch?v=MQKD-ZZeMD8&t=345s

![Xbox RP2040](https://github.com/user-attachments/assets/bf07470b-0496-45cd-ad8c-650e52522f54)

**Comment by Electrical5** [comment]
Yes, we're getting quite some reports of counterfeit RP2040 boards that do not work properly.

Does this RP2040-Tiny have the 'WaveShare' logo on the back?
![image](https://github.com/user-attachments/assets/24931e64-fa55-431c-8997-b24bc0a24d0f)

Could you try installing PrometheOS and checking what color the LED lights up to when you connect it to the xbox and start up the xbox?
[RP2040 Zero Prometheos V1.4.0.zip](https://github.com/user-attachments/files/17213740/RP2040.Zero.Prometheos.V1.4.0.zip)

**Comment by danko79** [comment]
Hi, assembled another one with RP2040-Zero works fine, the problems is the RP2040-Zero Tiny no logo waveshare.
