### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by dcook101** [Electrical5/ModXo-RP2040-Zero#2]
Hello, most of the components required look straightforward enough. 
I wasn't sure what type of Diode to purchase for this adapter board?
Apologies I'm totally new to this.

Thanks

**Comment by danko79** [comment]
1 RP2040-Zero
4 pcs 100R 1/4w resitors
1 pcs diode 1N4148 optional

**Comment by Electrical5** [comment]
Yes practically any diode works.
Also, the diode is only really required if you connect both the xbox and PC at the same time.
